site_name: RememberThis
docs_dir: core/components/rememberthis/docs
site_dir: _build/site

repo_url: https://github.com/Jako/RememberThis

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables